preprocessing:
  dataset_type: segmenter # chosse between 'segmenter', 'fusion' and 'both'
  tiles_location: D:\Terranum_SD\99_Data\Playground\data_2048\test
  results_location: data/preprocessing
  suffixe: test
  segmenter:
    base_squares: [256, 512, 768, 1024]
    scales: [1.0, 0.75, 0.5, 0.25]
    sample_size: 512
    num_samples_per_tile: 1
  fusion:
    sample_size: 2048
    central_square: 1024