segmenter:
  num_epochs: 1
  batch_size: 4
  num_workers: 4
  dataset: data/dataset_segmentation_landslide
fusion:
  num_epochs: 1
  batch_size: 2
  num_workers: 2
  dataset: data/dataset_fusion_landslide