output_dir: "results/training"
# output_suffixe: fusion_modulus_dice_focal_loss
output_suffixe: test
# output_suffixe: test
# output_suffixe: Bern_v2_focal_dice_losses
val_split: 0.1
num_epochs: 2
batch_size: 4
num_workers: 4
learning_rate: 5e-5
weight_decay: 0.01

is_trained: fusion  # choose between segmenter and fusion
scales: [1.0, 0.75, 0.5, 0.25]
from_pretrain: False
# pretrain_dir: results/training/20260107_173803_50_epochs_Longxi_Bern_v2_focal_dice_losses
# pretrain_dir: results/training/20260122_225022_100_epochs_Longxihe_Bern_v2_focal_dice_losses_with_900_false_pos_from_scratch_da_scale
pretrain_dir: results/training/20260211_172648_segmenter_50_epochs_multi_resolution
resume_from_existing: False
existing_dir: results/training/20260120_112049_50_epochs_Bern_v2_focal_dice_losses_with_1800_false_pos_from_scratch

do_data_augmentation: True
do_da_scaling: False
do_save_best_preds: False

pretrained_model: nvidia/segformer-b0-finetuned-ade-512-512
# save_preds_lbls: True


# list of pretrained models:
# nvidia/segformer-b0-finetuned-ade-512-512
# nvidia/segformer-b0-finetuned-cityscapes-1024-1024
# nvidia/segformer-b0-finetuned-cityscapes-512-1024
# nvidia/segformer-b0-finetuned-cityscapes-640-1280
# nvidia/segformer-b0-finetuned-cityscapes-768-768
# nvidia/segformer-b1-finetuned-ade-512-512
# nvidia/segformer-b1-finetuned-cityscapes-1024-1024
# lsi55/ddpm-ema-nvidia-segformer-b1-finetuned-cityscapes-1024-1024
# nvidia/segformer-b2-finetuned-cityscapes-1024-1024
# nvidia/segformer-b2-finetuned-ade-512-512
# nvidia/segformer-b3-finetuned-ade-512-512
# nvidia/segformer-b3-finetuned-cityscapes-1024-1024
# nvidia/segformer-b4-finetuned-ade-512-512
# nvidia/segformer-b4-finetuned-cityscapes-1024-1024
# nvidia/segformer-b5-finetuned-ade-640-640
# nvidia/segformer-b5-finetuned-cityscapes-1024-1024
# janakipanneerselvam/SegFormer_Sunlit_nvidia_mit-b5
# janakipanneerselvam/SegFormer_Sunlit_nvidia_mit-b5_v2
# janakipanneerselvam/SegFormer_Sunlit_nvidia_mit-b5_Almonds
# janakipanneerselvam/Almond_SegFormer_Sunlit_nvidia_mit-b5